name: Test unit prices
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Build docker container
        run: docker build -t grocy_test tests

      - name: Start docker container
        run: docker run -d -p 9283:80 grocy_test

      - uses: actions/cache@v2
        name: Cache python environment
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements_dev.txt') }}

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      - name: Install dev requirements
        run: python -m pip install -r requirements_dev.txt

      - name: Wait for grocy to be available
        run: python3 tests/http_wait.py

      - name: Run tests
        run: coverage run -m unittest

      - name: Convert coverage
        run: coverage xml

      - name: Upload coverage
        uses: codecov/codecov-action@v2
